
some notes

的当机立断


大家都来的

的的结论是了多分


djdld  ddldf 

bjgcjs


bsbas
sabj

脚后跟换句话vhv

昆明看来都没看蓝

测试

```{python}
3+2
```

```{r}
4+5
```

djdldl
谢欣悦1
王悦
廖明可123
梁依婷
陈瑶
# The Diary of Five Golden Flowers
陈瑶的日记1
Date:2020.6.14
学习上：1.整理昨天上课的笔记。
2.看了markdown的写作方面的资料，完善毕业论文中的一些代码。
3.看了些西瓜书的内容。
生活上：做了点家务，运动运动，保持好心情。

王悦的日记1
2020年6月14日
1.整理昨天的笔记
2.完善毕业论文的相关事宜以及填各种表格
3.背单词打卡
4.阅读
5.锻炼

梁依婷的日记 day1 
2020/06/14
1.测试cpu性能和硬盘属性
2.整理并上传省优秀毕业生宣传文件
3.大扫除
4.整理毕业季照片、完善毕业宣传拍摄
5.锻炼

廖明可的日记
2020年6月14日 晴
1.背英语单词
2.阅读markdown写作指导材料，重新架构毕业论文写作及排版框架
3.休息时间补看最新一期《最强大脑》
4.日常打扫卫生
5.跟着锻炼视频运动一小时

陈瑶的日记2
Date:2020.6.15
学习上：1.看西瓜书。
2.阅读markdown相关资料。
3.看英语材料
生活上：呼啦圈、仰卧起坐、散步。

王悦的日记2
2020年6月15日
1.写日程本
2.阅读
3.背单词打卡
4.复习markdown的资料
5.锻炼

谢欣悦的日记1（补昨天的==抱歉）
2020.6.14 离校的倒数第二天
返校的日子真的太“充实”了，前一段时间一直在整理学校的各种文件资料，今天一天也做了很多事情哈哈哈哈  
1、和室友一起把书整理了然后卖了 看到自己的考研复习资料和一本本笔记 满满的心血 好舍不得 但是又带不走它们 眼睁睁地亲手把它们卖掉 心疼...
2、学校不允许外出 在食堂和室友们一起吃了“散伙饭” 有一丝丝感伤 不过吃得还挺开心哈哈哈
3、在寝室一直整理收拾东西 因为明天就要走啦 大包小包 装箱打包 体力消耗+10086

谢欣悦的日记2
2020.6.15 
1、办理了离校申请 和辅导员告别的时候 突然开始难过
2、把行李邮寄回家 几十公斤的包裹拖到宿舍楼下 体力消耗upup
3、和室友一起拍了告别学校的视频 和学校的一花一树 一草一木说再见
4、要走的时候突然狂风暴雨 或许学校也是在以这种方式表达对我们的不舍吧
5、今日尤其伤感 在相互的拥抱和泪眼中就这样说再见啦 未来都会更好的 一起加油鸭！

梁依婷的日记2
2020.6.15
1.选择新电脑，型号做功课
2.部门道别，聚餐
3.和室友夜跑，绕学校西操场十圈
4.整理衣物，清理回收
5.看书

陈瑶的日记3
Date:2020.6.16
学习上：1.看了点英语。
2.接着完善论文，并上传论文及其所需的图片。
3.看了点西瓜书
生活上：运动运动、娱乐娱乐。

梁依婷的日记3
2020.6.16
1.看时事新闻，整理思想汇报
2.录校毕业生大合唱《不忘初心》户外视频
3.选购新电脑
4.锻炼
5.整理笔记
6.联系暑期实习

廖明可的日记
2020年6月15日 晴
1.背英语单词
2.markdown毕业论文写作，尤其是学习了表格和图片的编辑
3.买食材做了简单的一餐
4.锻炼一小时
2020年6月16日 晴
1.背英语单词
2.继续进行markdown毕业论文写作
3.看了些视频放松一下
4.锻炼一小时

谢欣悦的日记3
2020.6.16
1.整理了开会的内容和markdown写作的笔记
2.包裹已收到 然后收拾整理了房间和衣物
3.看了些课外书和喜欢的综艺嘿嘿
4.晚饭后和家人一起出门散步 白天一直下雨 晚上雨停了 天气凉凉的 很舒服

王悦的日记3
2020年6月16日
1.阅读一小时
2.背单词打卡
3.复习markdown资料
4.618买了好多想买的 疯狂剁手
5.锻炼

陈瑶的日记4
Date:2020.6.17
学习上：1.昨天上传文件传错了位置，又手动删除，再上传（5555555）。
然后今天上传也遇到了点问题，不知道为啥所有的文件都传上去了，再把多余的给删除了。
2.把论文再完善了，学习了表格的写法。
生活上：运动、听音乐and so on...

王悦的日记4
2020年6月17日
1.阅读
2.背单词打卡
3.锻炼
4.下雨天出门拿了快递顺便赏雨……

谢欣悦的日记4
2020.6.17
1.整理并完善了markdown毕业论文写作
2.上传了rmd文件和毕业论文中的图片（我新建了一个文件夹上传的 但是无法生成网页 转成网页的时候显示找不到html文件 是只能在rmd-article-template中上传么 我的脑子空空如也)
3.刚到家 学校又有东西让去领一下 只能等之后邮寄了（我太难辽...)
4.拍的毕业照被选上学院的优秀毕业照了 开心~最近打算整理一波大学四年的照片 回忆青春哈哈哈哈
5.又下了一天的雨 希望快快晴起来

梁依婷的日记4
2020.6.17
1.看书/看时事新闻
2.整理笔记
3.室友聚餐加户外合影
4.打包部分行李寄回家
5.确定毕业音乐节表演歌曲，与合作同学分part合作表演

廖明可的日记
2020年6月17日 晴
1.背单词
2.markdown写作进入最后冲刺阶段
3.锻炼一小时
4.看综艺
5.618又买了一些东西，今天要开始陆续收快递了（拆快递令人开心！）

梁依婷的日记5
2020.6.18
1.回看部分618晚会节目，the9大势冲冲冲！
2.新电脑激活安装/重要软件按原先操作重新安装
3.领到学士服套装了，毕业季的实感，有点舍不得大家
4.练书法
5.锻炼

王悦的日记5
2020年6月18日
1.阅读
2.背单词打卡
3.锻炼
4.看剧
5.拿快递拆快递

陈瑶的日记5
Date:2020.6.18
学习上：听了一些英语，看新闻。
生活上：做一些家务、锻炼、跟同学计划明天出去玩~（exciting...）

谢欣悦的日记5
2020.6.18
1.昨天上传文件出现的问题 今天搞好了！我又可以啦！！
2.去超市买了菜、水果和一些好吃的
3.收拾屋子 整理了照片 准备打印一些照片做个相册
4.晚饭后出去溜达了一圈 今天没下雨啦~

梁依婷的日记6
2020.6.19
1.打扫卫生，照例
2.升学前的暑期短期实习还没有敲定，疯狂投简历，希望有机会收到心仪的offer
3.物色适合的房源，短租毕业生太难了，社畜真心酸
4.看了罗伯莱纳导演的电影《The Bucket List》，讲述的是两个患了末期癌症的病人机缘
巧合成为朋友，并一起度过余下的日子的故事。治愈系电影我滴爱！

王悦的日记6
2020年6月19日
1.今天和朋友出去走走，聊聊天，祝贺她终于一志愿上岸了
2.全手动拍立得挑战再次失败，五张拍立得全部报废，嗯好多钱，为什么在晚上拍就特别容易黑呢？
3.但是新买的相机包很可爱
4.拿快递拆快递
5.日常锻炼

陈瑶的日记6
Date:2020.6.18
1.今天跟好久没见的几个高中同学见面了，开心开心。
2.一起去几何书店，书店的氛围很好，还可以自己做烘焙~
3.去万达买了衣服等等。shopping~
4.一起去吃了海底捞~
5.去胜利路溜达~大家一起交流，互换想法。
6.最大的感触就是虽然很久没见，但是大家还是应接既往的亲近~每个人都成长了，都有别
人值得学习的闪光点~希望大家都可以变成自己想要的模样~冲丫！！！

谢欣悦的日记6
2020.6.19
1.又理了东西、书和零零散散的小物件 有些想扔掉又觉得以后会用到 有些一直搜集着又舍不得扔哈哈哈 
2.给朋友挑选了生日礼物 希望她会喜欢嘿嘿
3.和奶奶一起唠了很久的嗑 她讲着我听着~
4.看书 追剧（姐姐更新啦 我的快乐源泉哈哈哈哈！）
5.饭后又出去散步消食啦~

廖明可的（不知道什么时候能提交成功的）日记
2020年6月18日 晴转阴
1.背单词
2.完成了毕业论文markdown写作，在上传的时候遇到问题，一直循环进行github认证，只能
明天再说了...
3.看综艺
4.锻炼一小时
2020年6月19日 雨
1.背单词
2.终于把论文相关材料提交成功啦！（也折腾了好久...)
3.整理档案所需材料
4.打扫卫生
5.锻炼一小时